package com.lgiter.practice.freemarker;

import com.alibaba.fastjson.JSON;
import com.lgiter.practice.freemarker.bean.Animals;
import com.lgiter.practice.freemarker.bean.Student;
import com.lgiter.practice.freemarker.funtion.GroupByMethod;
import com.oracle.tools.packager.Log;
import com.sun.corba.se.impl.orbutil.ObjectWriter;
import com.sun.tracing.dtrace.ArgsAttributes;
import freemarker.cache.ClassTemplateLoader;
import freemarker.template.Configuration;
import freemarker.template.Template;
import freemarker.template.TemplateException;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.extern.slf4j.Slf4j;
import org.junit.Before;
import org.junit.Test;

import java.io.IOException;
import java.io.StringWriter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Stack;
import java.util.function.Function;
import java.util.stream.Collectors;

/**
 * @Author: lixiaolong
 * @Description: freemarker学习
 * @Date: 2021/9/27
 */
@Slf4j
public class FreemarkerDemo {

    private static Configuration config = new Configuration(Configuration.VERSION_2_3_31);
    private static Map<String, Object> map = new HashMap<>();

    @Before
    public void before() {
        final ClassTemplateLoader loader = new ClassTemplateLoader(Hello.class, "/template");
        config.setTemplateLoader(loader);
        config.setSharedVariable("group_by",new GroupByMethod());
        map.clear();
    }


    @Test
    public void helloWorld() throws Exception {
        Template template = config.getTemplate("hello.ftl");
        map.put("content", "Hello World");
        StringWriter stringWriter = new StringWriter();

        template.process(map, stringWriter);
        String s = stringWriter.getBuffer().toString();
        System.out.println(s);
    }

    @Test
    public void list() throws Exception {
        List<Animals> animals = Arrays.asList(
                new Animals("狗1", 4),
                new Animals("狗2", 4),
                new Animals("狗3", 4)
        );
        map.put("animals",animals);
        StringWriter stringWriter = new StringWriter();
        Template template = config.getTemplate("list.ftl");
        template.process(map, stringWriter);
        String s = stringWriter.getBuffer().toString();
        System.out.println(s);
    }

    @Test
    public void macro() throws Exception {
        List<Animals> list = Arrays.asList(
                new Animals("狗1", 4),
                new Animals("狗2", 4),
                new Animals("狗3", 4)
        );
        map.put("animals",list);
        StringWriter stringWriter = new StringWriter();
        Template template = config.getTemplate("macro.ftl");
        template.process(map, stringWriter);
        String s = stringWriter.getBuffer().toString();
        System.out.println(s);
    }

    @Test
    public void groupby() throws Exception{
        Student s1 = new Student("S1", "B1","A1");
        Student s2 = new Student("S1", "B1","A1");
        Student s3 = new Student("S1", "B2","A1");
        Student s4 = new Student("S2", "B1","A2");
        Student s5 = new Student("S23", "B2","A2");
        Student s6 = new Student("S2", "B3","A2");
        Student s8 = new Student("S1", "B1","A3");
        Student s9 = new Student("S1", "B1","A4");
        Student s10 = new Student("S9", "B1","A4");
        Student s11 = new Student("S10", "B1","A5");
        s10.setGrade2("L");
        s11.setGrade2("L");
        s9.setGrade2("L");
        List<Student> list = Arrays.asList(s1, s2, s3, s4, s5, s6, s8,s9,s10,s11);

        map.put("list",list);
        StringWriter stringWriter = new StringWriter();
        Template template = config.getTemplate("mygroupby.ftl");
        template.process(map, stringWriter);
        String s = stringWriter.getBuffer().toString();
        System.out.println(s);
    }

    @Test
    public void cxoTest() throws Exception{
        String mapString = "{\n" +
                "    \"payload\":{\n" +
                "        \"columns\":[\n" +
                "            {\n" +
                "                \"fieldRemark\":\"\",\n" +
                "                \"name\":\"data_time\",\n" +
                "                \"type\":\"VARCHAR\"\n" +
                "            },\n" +
                "            {\n" +
                "                \"fieldRemark\":\"\",\n" +
                "                \"name\":\"total_wait_delivery\",\n" +
                "                \"type\":\"DECIMAL\"\n" +
                "            },\n" +
                "            {\n" +
                "                \"fieldRemark\":\"\",\n" +
                "                \"name\":\"l7_wait_delivery\",\n" +
                "                \"type\":\"DECIMAL\"\n" +
                "            },\n" +
                "            {\n" +
                "                \"fieldRemark\":\"\",\n" +
                "                \"name\":\"l8_wait_delivery\",\n" +
                "                \"type\":\"DECIMAL\"\n" +
                "            },\n" +
                "            {\n" +
                "                \"fieldRemark\":\"\",\n" +
                "                \"name\":\"l9_wait_delivery\",\n" +
                "                \"type\":\"DECIMAL\"\n" +
                "            },\n" +
                "            {\n" +
                "                \"fieldRemark\":\"\",\n" +
                "                \"name\":\"one_wait_delivery\",\n" +
                "                \"type\":\"DECIMAL\"\n" +
                "            },\n" +
                "            {\n" +
                "                \"fieldRemark\":\"\",\n" +
                "                \"name\":\"l7_air_wait_delivery\",\n" +
                "                \"type\":\"DECIMAL\"\n" +
                "            },\n" +
                "            {\n" +
                "                \"fieldRemark\":\"\",\n" +
                "                \"name\":\"l7_pro_wait_delivery\",\n" +
                "                \"type\":\"DECIMAL\"\n" +
                "            },\n" +
                "            {\n" +
                "                \"fieldRemark\":\"\",\n" +
                "                \"name\":\"l7_max_wait_delivery\",\n" +
                "                \"type\":\"DECIMAL\"\n" +
                "            },\n" +
                "            {\n" +
                "                \"fieldRemark\":\"\",\n" +
                "                \"name\":\"l8_air_wait_delivery\",\n" +
                "                \"type\":\"DECIMAL\"\n" +
                "            },\n" +
                "            {\n" +
                "                \"fieldRemark\":\"\",\n" +
                "                \"name\":\"l8_pro_wait_delivery\",\n" +
                "                \"type\":\"DECIMAL\"\n" +
                "            },\n" +
                "            {\n" +
                "                \"fieldRemark\":\"\",\n" +
                "                \"name\":\"l8_max_wait_delivery\",\n" +
                "                \"type\":\"DECIMAL\"\n" +
                "            },\n" +
                "            {\n" +
                "                \"fieldRemark\":\"\",\n" +
                "                \"name\":\"l7_lock_wait_delivery\",\n" +
                "                \"type\":\"DECIMAL\"\n" +
                "            },\n" +
                "            {\n" +
                "                \"fieldRemark\":\"\",\n" +
                "                \"name\":\"l7_intent_wait_delivery\",\n" +
                "                \"type\":\"DECIMAL\"\n" +
                "            },\n" +
                "            {\n" +
                "                \"fieldRemark\":\"\",\n" +
                "                \"name\":\"l7_from_l9_wait_delivery\",\n" +
                "                \"type\":\"DECIMAL\"\n" +
                "            },\n" +
                "            {\n" +
                "                \"fieldRemark\":\"\",\n" +
                "                \"name\":\"l7_from_l8_wait_delivery\",\n" +
                "                \"type\":\"DECIMAL\"\n" +
                "            },\n" +
                "            {\n" +
                "                \"fieldRemark\":\"\",\n" +
                "                \"name\":\"l7_from_one_wait_delivery\",\n" +
                "                \"type\":\"DECIMAL\"\n" +
                "            },\n" +
                "            {\n" +
                "                \"fieldRemark\":\"\",\n" +
                "                \"name\":\"l8_lock_wait_delivery\",\n" +
                "                \"type\":\"DECIMAL\"\n" +
                "            },\n" +
                "            {\n" +
                "                \"fieldRemark\":\"\",\n" +
                "                \"name\":\"l8_from_l9_wait_delivery\",\n" +
                "                \"type\":\"DECIMAL\"\n" +
                "            },\n" +
                "            {\n" +
                "                \"fieldRemark\":\"\",\n" +
                "                \"name\":\"l8_from_l7_wait_delivery\",\n" +
                "                \"type\":\"DECIMAL\"\n" +
                "            },\n" +
                "            {\n" +
                "                \"fieldRemark\":\"\",\n" +
                "                \"name\":\"l8_from_one_wait_delivery\",\n" +
                "                \"type\":\"DECIMAL\"\n" +
                "            },\n" +
                "            {\n" +
                "                \"fieldRemark\":\"\",\n" +
                "                \"name\":\"l9_lock_wait_delivery\",\n" +
                "                \"type\":\"DECIMAL\"\n" +
                "            },\n" +
                "            {\n" +
                "                \"fieldRemark\":\"\",\n" +
                "                \"name\":\"l9_intent_wait_delivery\",\n" +
                "                \"type\":\"DECIMAL\"\n" +
                "            },\n" +
                "            {\n" +
                "                \"fieldRemark\":\"\",\n" +
                "                \"name\":\"l9_from_l8_wait_delivery\",\n" +
                "                \"type\":\"DECIMAL\"\n" +
                "            },\n" +
                "            {\n" +
                "                \"fieldRemark\":\"\",\n" +
                "                \"name\":\"l9_from_l7_wait_delivery\",\n" +
                "                \"type\":\"DECIMAL\"\n" +
                "            },\n" +
                "            {\n" +
                "                \"fieldRemark\":\"\",\n" +
                "                \"name\":\"l9_from_one_wait_delivery\",\n" +
                "                \"type\":\"DECIMAL\"\n" +
                "            },\n" +
                "            {\n" +
                "                \"fieldRemark\":\"\",\n" +
                "                \"name\":\"one_lock_wait_delivery\",\n" +
                "                \"type\":\"DECIMAL\"\n" +
                "            },\n" +
                "            {\n" +
                "                \"fieldRemark\":\"\",\n" +
                "                \"name\":\"one_from_l9_wait_delivery\",\n" +
                "                \"type\":\"DECIMAL\"\n" +
                "            },\n" +
                "            {\n" +
                "                \"fieldRemark\":\"\",\n" +
                "                \"name\":\"one_from_l8_wait_delivery\",\n" +
                "                \"type\":\"DECIMAL\"\n" +
                "            },\n" +
                "            {\n" +
                "                \"fieldRemark\":\"\",\n" +
                "                \"name\":\"one_from_l7_wait_delivery\",\n" +
                "                \"type\":\"DECIMAL\"\n" +
                "            },\n" +
                "            {\n" +
                "                \"fieldRemark\":\"\",\n" +
                "                \"name\":\"seq_num\",\n" +
                "                \"type\":\"BIGINT\"\n" +
                "            }\n" +
                "        ],\n" +
                "        \"fromCache\":false,\n" +
                "        \"pageNo\":1,\n" +
                "        \"pageSize\":100,\n" +
                "        \"resultList\":[\n" +
                "            {\n" +
                "                \"data_time\":\"2023.02.11\",\n" +
                "                \"total_wait_delivery\":16148,\n" +
                "                \"l7_wait_delivery\":3720,\n" +
                "                \"l8_wait_delivery\":5682,\n" +
                "                \"l9_wait_delivery\":6360,\n" +
                "                \"one_wait_delivery\":386,\n" +
                "                \"l7_air_wait_delivery\":228,\n" +
                "                \"l7_pro_wait_delivery\":2184,\n" +
                "                \"l7_max_wait_delivery\":1308,\n" +
                "                \"l8_air_wait_delivery\":37,\n" +
                "                \"l8_pro_wait_delivery\":4480,\n" +
                "                \"l8_max_wait_delivery\":1165,\n" +
                "                \"l7_lock_wait_delivery\":730,\n" +
                "                \"l7_intent_wait_delivery\":2875,\n" +
                "                \"l7_from_l9_wait_delivery\":51,\n" +
                "                \"l7_from_l8_wait_delivery\":63,\n" +
                "                \"l7_from_one_wait_delivery\":1,\n" +
                "                \"l8_lock_wait_delivery\":5339,\n" +
                "                \"l8_from_l9_wait_delivery\":285,\n" +
                "                \"l8_from_l7_wait_delivery\":22,\n" +
                "                \"l8_from_one_wait_delivery\":36,\n" +
                "                \"l9_lock_wait_delivery\":5392,\n" +
                "                \"l9_intent_wait_delivery\":799,\n" +
                "                \"l9_from_l8_wait_delivery\":151,\n" +
                "                \"l9_from_l7_wait_delivery\":7,\n" +
                "                \"l9_from_one_wait_delivery\":11,\n" +
                "                \"one_lock_wait_delivery\":373,\n" +
                "                \"one_from_l9_wait_delivery\":6,\n" +
                "                \"one_from_l8_wait_delivery\":7,\n" +
                "                \"one_from_l7_wait_delivery\":0,\n" +
                "                \"seq_num\":31\n" +
                "            },\n" +
                "            {\n" +
                "                \"data_time\":\"2023.02.12\",\n" +
                "                \"total_wait_delivery\":17003,\n" +
                "                \"l7_wait_delivery\":4466,\n" +
                "                \"l8_wait_delivery\":5736,\n" +
                "                \"l9_wait_delivery\":6390,\n" +
                "                \"one_wait_delivery\":411,\n" +
                "                \"l7_air_wait_delivery\":288,\n" +
                "                \"l7_pro_wait_delivery\":2684,\n" +
                "                \"l7_max_wait_delivery\":1494,\n" +
                "                \"l8_air_wait_delivery\":47,\n" +
                "                \"l8_pro_wait_delivery\":4516,\n" +
                "                \"l8_max_wait_delivery\":1173,\n" +
                "                \"l7_lock_wait_delivery\":1039,\n" +
                "                \"l7_intent_wait_delivery\":3297,\n" +
                "                \"l7_from_l9_wait_delivery\":59,\n" +
                "                \"l7_from_l8_wait_delivery\":70,\n" +
                "                \"l7_from_one_wait_delivery\":1,\n" +
                "                \"l8_lock_wait_delivery\":5391,\n" +
                "                \"l8_from_l9_wait_delivery\":283,\n" +
                "                \"l8_from_l7_wait_delivery\":27,\n" +
                "                \"l8_from_one_wait_delivery\":35,\n" +
                "                \"l9_lock_wait_delivery\":5432,\n" +
                "                \"l9_intent_wait_delivery\":787,\n" +
                "                \"l9_from_l8_wait_delivery\":149,\n" +
                "                \"l9_from_l7_wait_delivery\":11,\n" +
                "                \"l9_from_one_wait_delivery\":11,\n" +
                "                \"one_lock_wait_delivery\":398,\n" +
                "                \"one_from_l9_wait_delivery\":6,\n" +
                "                \"one_from_l8_wait_delivery\":7,\n" +
                "                \"one_from_l7_wait_delivery\":0,\n" +
                "                \"seq_num\":30\n" +
                "            },\n" +
                "            {\n" +
                "                \"data_time\":\"2023.02.13\",\n" +
                "                \"total_wait_delivery\":17063,\n" +
                "                \"l7_wait_delivery\":4889,\n" +
                "                \"l8_wait_delivery\":5589,\n" +
                "                \"l9_wait_delivery\":6184,\n" +
                "                \"one_wait_delivery\":401,\n" +
                "                \"l7_air_wait_delivery\":319,\n" +
                "                \"l7_pro_wait_delivery\":2977,\n" +
                "                \"l7_max_wait_delivery\":1593,\n" +
                "                \"l8_air_wait_delivery\":55,\n" +
                "                \"l8_pro_wait_delivery\":4375,\n" +
                "                \"l8_max_wait_delivery\":1159,\n" +
                "                \"l7_lock_wait_delivery\":1213,\n" +
                "                \"l7_intent_wait_delivery\":3520,\n" +
                "                \"l7_from_l9_wait_delivery\":70,\n" +
                "                \"l7_from_l8_wait_delivery\":85,\n" +
                "                \"l7_from_one_wait_delivery\":1,\n" +
                "                \"l8_lock_wait_delivery\":5262,\n" +
                "                \"l8_from_l9_wait_delivery\":271,\n" +
                "                \"l8_from_l7_wait_delivery\":24,\n" +
                "                \"l8_from_one_wait_delivery\":32,\n" +
                "                \"l9_lock_wait_delivery\":5244,\n" +
                "                \"l9_intent_wait_delivery\":771,\n" +
                "                \"l9_from_l8_wait_delivery\":146,\n" +
                "                \"l9_from_l7_wait_delivery\":12,\n" +
                "                \"l9_from_one_wait_delivery\":11,\n" +
                "                \"one_lock_wait_delivery\":388,\n" +
                "                \"one_from_l9_wait_delivery\":6,\n" +
                "                \"one_from_l8_wait_delivery\":7,\n" +
                "                \"one_from_l7_wait_delivery\":0,\n" +
                "                \"seq_num\":29\n" +
                "            },\n" +
                "            {\n" +
                "                \"data_time\":\"2023.02.14\",\n" +
                "                \"total_wait_delivery\":17300,\n" +
                "                \"l7_wait_delivery\":5388,\n" +
                "                \"l8_wait_delivery\":5462,\n" +
                "                \"l9_wait_delivery\":6058,\n" +
                "                \"one_wait_delivery\":392,\n" +
                "                \"l7_air_wait_delivery\":351,\n" +
                "                \"l7_pro_wait_delivery\":3322,\n" +
                "                \"l7_max_wait_delivery\":1715,\n" +
                "                \"l8_air_wait_delivery\":58,\n" +
                "                \"l8_pro_wait_delivery\":4261,\n" +
                "                \"l8_max_wait_delivery\":1143,\n" +
                "                \"l7_lock_wait_delivery\":1462,\n" +
                "                \"l7_intent_wait_delivery\":3749,\n" +
                "                \"l7_from_l9_wait_delivery\":81,\n" +
                "                \"l7_from_l8_wait_delivery\":93,\n" +
                "                \"l7_from_one_wait_delivery\":3,\n" +
                "                \"l8_lock_wait_delivery\":5133,\n" +
                "                \"l8_from_l9_wait_delivery\":269,\n" +
                "                \"l8_from_l7_wait_delivery\":29,\n" +
                "                \"l8_from_one_wait_delivery\":31,\n" +
                "                \"l9_lock_wait_delivery\":5141,\n" +
                "                \"l9_intent_wait_delivery\":761,\n" +
                "                \"l9_from_l8_wait_delivery\":137,\n" +
                "                \"l9_from_l7_wait_delivery\":10,\n" +
                "                \"l9_from_one_wait_delivery\":9,\n" +
                "                \"one_lock_wait_delivery\":379,\n" +
                "                \"one_from_l9_wait_delivery\":6,\n" +
                "                \"one_from_l8_wait_delivery\":7,\n" +
                "                \"one_from_l7_wait_delivery\":0,\n" +
                "                \"seq_num\":28\n" +
                "            },\n" +
                "            {\n" +
                "                \"data_time\":\"2023.02.15\",\n" +
                "                \"total_wait_delivery\":17178,\n" +
                "                \"l7_wait_delivery\":5694,\n" +
                "                \"l8_wait_delivery\":5236,\n" +
                "                \"l9_wait_delivery\":5864,\n" +
                "                \"one_wait_delivery\":384,\n" +
                "                \"l7_air_wait_delivery\":369,\n" +
                "                \"l7_pro_wait_delivery\":3517,\n" +
                "                \"l7_max_wait_delivery\":1808,\n" +
                "                \"l8_air_wait_delivery\":61,\n" +
                "                \"l8_pro_wait_delivery\":4071,\n" +
                "                \"l8_max_wait_delivery\":1104,\n" +
                "                \"l7_lock_wait_delivery\":1612,\n" +
                "                \"l7_intent_wait_delivery\":3880,\n" +
                "                \"l7_from_l9_wait_delivery\":96,\n" +
                "                \"l7_from_l8_wait_delivery\":103,\n" +
                "                \"l7_from_one_wait_delivery\":3,\n" +
                "                \"l8_lock_wait_delivery\":4903,\n" +
                "                \"l8_from_l9_wait_delivery\":273,\n" +
                "                \"l8_from_l7_wait_delivery\":29,\n" +
                "                \"l8_from_one_wait_delivery\":31,\n" +
                "                \"l9_lock_wait_delivery\":4972,\n" +
                "                \"l9_intent_wait_delivery\":733,\n" +
                "                \"l9_from_l8_wait_delivery\":140,\n" +
                "                \"l9_from_l7_wait_delivery\":11,\n" +
                "                \"l9_from_one_wait_delivery\":8,\n" +
                "                \"one_lock_wait_delivery\":370,\n" +
                "                \"one_from_l9_wait_delivery\":7,\n" +
                "                \"one_from_l8_wait_delivery\":7,\n" +
                "                \"one_from_l7_wait_delivery\":0,\n" +
                "                \"seq_num\":27\n" +
                "            },\n" +
                "            {\n" +
                "                \"data_time\":\"2023.02.16\",\n" +
                "                \"total_wait_delivery\":17163,\n" +
                "                \"l7_wait_delivery\":5988,\n" +
                "                \"l8_wait_delivery\":5105,\n" +
                "                \"l9_wait_delivery\":5696,\n" +
                "                \"one_wait_delivery\":374,\n" +
                "                \"l7_air_wait_delivery\":390,\n" +
                "                \"l7_pro_wait_delivery\":3711,\n" +
                "                \"l7_max_wait_delivery\":1887,\n" +
                "                \"l8_air_wait_delivery\":70,\n" +
                "                \"l8_pro_wait_delivery\":3960,\n" +
                "                \"l8_max_wait_delivery\":1075,\n" +
                "                \"l7_lock_wait_delivery\":1769,\n" +
                "                \"l7_intent_wait_delivery\":3990,\n" +
                "                \"l7_from_l9_wait_delivery\":110,\n" +
                "                \"l7_from_l8_wait_delivery\":116,\n" +
                "                \"l7_from_one_wait_delivery\":3,\n" +
                "                \"l8_lock_wait_delivery\":4745,\n" +
                "                \"l8_from_l9_wait_delivery\":296,\n" +
                "                \"l8_from_l7_wait_delivery\":33,\n" +
                "                \"l8_from_one_wait_delivery\":31,\n" +
                "                \"l9_lock_wait_delivery\":4827,\n" +
                "                \"l9_intent_wait_delivery\":704,\n" +
                "                \"l9_from_l8_wait_delivery\":144,\n" +
                "                \"l9_from_l7_wait_delivery\":10,\n" +
                "                \"l9_from_one_wait_delivery\":11,\n" +
                "                \"one_lock_wait_delivery\":364,\n" +
                "                \"one_from_l9_wait_delivery\":4,\n" +
                "                \"one_from_l8_wait_delivery\":6,\n" +
                "                \"one_from_l7_wait_delivery\":0,\n" +
                "                \"seq_num\":26\n" +
                "            },\n" +
                "            {\n" +
                "                \"data_time\":\"2023.02.17\",\n" +
                "                \"total_wait_delivery\":17159,\n" +
                "                \"l7_wait_delivery\":6276,\n" +
                "                \"l8_wait_delivery\":5025,\n" +
                "                \"l9_wait_delivery\":5505,\n" +
                "                \"one_wait_delivery\":353,\n" +
                "                \"l7_air_wait_delivery\":416,\n" +
                "                \"l7_pro_wait_delivery\":3913,\n" +
                "                \"l7_max_wait_delivery\":1947,\n" +
                "                \"l8_air_wait_delivery\":72,\n" +
                "                \"l8_pro_wait_delivery\":3924,\n" +
                "                \"l8_max_wait_delivery\":1029,\n" +
                "                \"l7_lock_wait_delivery\":1893,\n" +
                "                \"l7_intent_wait_delivery\":4094,\n" +
                "                \"l7_from_l9_wait_delivery\":146,\n" +
                "                \"l7_from_l8_wait_delivery\":140,\n" +
                "                \"l7_from_one_wait_delivery\":3,\n" +
                "                \"l8_lock_wait_delivery\":4631,\n" +
                "                \"l8_from_l9_wait_delivery\":322,\n" +
                "                \"l8_from_l7_wait_delivery\":39,\n" +
                "                \"l8_from_one_wait_delivery\":33,\n" +
                "                \"l9_lock_wait_delivery\":4674,\n" +
                "                \"l9_intent_wait_delivery\":666,\n" +
                "                \"l9_from_l8_wait_delivery\":142,\n" +
                "                \"l9_from_l7_wait_delivery\":12,\n" +
                "                \"l9_from_one_wait_delivery\":11,\n" +
                "                \"one_lock_wait_delivery\":342,\n" +
                "                \"one_from_l9_wait_delivery\":3,\n" +
                "                \"one_from_l8_wait_delivery\":8,\n" +
                "                \"one_from_l7_wait_delivery\":0,\n" +
                "                \"seq_num\":25\n" +
                "            },\n" +
                "            {\n" +
                "                \"data_time\":\"2023.02.18\",\n" +
                "                \"total_wait_delivery\":17512,\n" +
                "                \"l7_wait_delivery\":6717,\n" +
                "                \"l8_wait_delivery\":4990,\n" +
                "                \"l9_wait_delivery\":5439,\n" +
                "                \"one_wait_delivery\":366,\n" +
                "                \"l7_air_wait_delivery\":455,\n" +
                "                \"l7_pro_wait_delivery\":4213,\n" +
                "                \"l7_max_wait_delivery\":2049,\n" +
                "                \"l8_air_wait_delivery\":89,\n" +
                "                \"l8_pro_wait_delivery\":3890,\n" +
                "                \"l8_max_wait_delivery\":1011,\n" +
                "                \"l7_lock_wait_delivery\":2162,\n" +
                "                \"l7_intent_wait_delivery\":4260,\n" +
                "                \"l7_from_l9_wait_delivery\":149,\n" +
                "                \"l7_from_l8_wait_delivery\":143,\n" +
                "                \"l7_from_one_wait_delivery\":3,\n" +
                "                \"l8_lock_wait_delivery\":4605,\n" +
                "                \"l8_from_l9_wait_delivery\":314,\n" +
                "                \"l8_from_l7_wait_delivery\":38,\n" +
                "                \"l8_from_one_wait_delivery\":33,\n" +
                "                \"l9_lock_wait_delivery\":4632,\n" +
                "                \"l9_intent_wait_delivery\":651,\n" +
                "                \"l9_from_l8_wait_delivery\":135,\n" +
                "                \"l9_from_l7_wait_delivery\":10,\n" +
                "                \"l9_from_one_wait_delivery\":11,\n" +
                "                \"one_lock_wait_delivery\":353,\n" +
                "                \"one_from_l9_wait_delivery\":5,\n" +
                "                \"one_from_l8_wait_delivery\":8,\n" +
                "                \"one_from_l7_wait_delivery\":0,\n" +
                "                \"seq_num\":24\n" +
                "            },\n" +
                "            {\n" +
                "                \"data_time\":\"2023.02.19\",\n" +
                "                \"total_wait_delivery\":18118,\n" +
                "                \"l7_wait_delivery\":7156,\n" +
                "                \"l8_wait_delivery\":5103,\n" +
                "                \"l9_wait_delivery\":5450,\n" +
                "                \"one_wait_delivery\":409,\n" +
                "                \"l7_air_wait_delivery\":489,\n" +
                "                \"l7_pro_wait_delivery\":4525,\n" +
                "                \"l7_max_wait_delivery\":2142,\n" +
                "                \"l8_air_wait_delivery\":100,\n" +
                "                \"l8_pro_wait_delivery\":3972,\n" +
                "                \"l8_max_wait_delivery\":1031,\n" +
                "                \"l7_lock_wait_delivery\":2444,\n" +
                "                \"l7_intent_wait_delivery\":4406,\n" +
                "                \"l7_from_l9_wait_delivery\":155,\n" +
                "                \"l7_from_l8_wait_delivery\":148,\n" +
                "                \"l7_from_one_wait_delivery\":3,\n" +
                "                \"l8_lock_wait_delivery\":4714,\n" +
                "                \"l8_from_l9_wait_delivery\":312,\n" +
                "                \"l8_from_l7_wait_delivery\":43,\n" +
                "                \"l8_from_one_wait_delivery\":34,\n" +
                "                \"l9_lock_wait_delivery\":4652,\n" +
                "                \"l9_intent_wait_delivery\":639,\n" +
                "                \"l9_from_l8_wait_delivery\":135,\n" +
                "                \"l9_from_l7_wait_delivery\":13,\n" +
                "                \"l9_from_one_wait_delivery\":11,\n" +
                "                \"one_lock_wait_delivery\":395,\n" +
                "                \"one_from_l9_wait_delivery\":6,\n" +
                "                \"one_from_l8_wait_delivery\":8,\n" +
                "                \"one_from_l7_wait_delivery\":0,\n" +
                "                \"seq_num\":23\n" +
                "            },\n" +
                "            {\n" +
                "                \"data_time\":\"2023.02.20\",\n" +
                "                \"total_wait_delivery\":18045,\n" +
                "                \"l7_wait_delivery\":7422,\n" +
                "                \"l8_wait_delivery\":5005,\n" +
                "                \"l9_wait_delivery\":5229,\n" +
                "                \"one_wait_delivery\":389,\n" +
                "                \"l7_air_wait_delivery\":493,\n" +
                "                \"l7_pro_wait_delivery\":4728,\n" +
                "                \"l7_max_wait_delivery\":2201,\n" +
                "                \"l8_air_wait_delivery\":105,\n" +
                "                \"l8_pro_wait_delivery\":3888,\n" +
                "                \"l8_max_wait_delivery\":1012,\n" +
                "                \"l7_lock_wait_delivery\":2597,\n" +
                "                \"l7_intent_wait_delivery\":4497,\n" +
                "                \"l7_from_l9_wait_delivery\":169,\n" +
                "                \"l7_from_l8_wait_delivery\":155,\n" +
                "                \"l7_from_one_wait_delivery\":4,\n" +
                "                \"l8_lock_wait_delivery\":4604,\n" +
                "                \"l8_from_l9_wait_delivery\":316,\n" +
                "                \"l8_from_l7_wait_delivery\":52,\n" +
                "                \"l8_from_one_wait_delivery\":33,\n" +
                "                \"l9_lock_wait_delivery\":4456,\n" +
                "                \"l9_intent_wait_delivery\":618,\n" +
                "                \"l9_from_l8_wait_delivery\":132,\n" +
                "                \"l9_from_l7_wait_delivery\":12,\n" +
                "                \"l9_from_one_wait_delivery\":11,\n" +
                "                \"one_lock_wait_delivery\":374,\n" +
                "                \"one_from_l9_wait_delivery\":6,\n" +
                "                \"one_from_l8_wait_delivery\":9,\n" +
                "                \"one_from_l7_wait_delivery\":0,\n" +
                "                \"seq_num\":22\n" +
                "            },\n" +
                "            {\n" +
                "                \"data_time\":\"2023.02.21\",\n" +
                "                \"total_wait_delivery\":17975,\n" +
                "                \"l7_wait_delivery\":7715,\n" +
                "                \"l8_wait_delivery\":4873,\n" +
                "                \"l9_wait_delivery\":4992,\n" +
                "                \"one_wait_delivery\":395,\n" +
                "                \"l7_air_wait_delivery\":516,\n" +
                "                \"l7_pro_wait_delivery\":4920,\n" +
                "                \"l7_max_wait_delivery\":2279,\n" +
                "                \"l8_air_wait_delivery\":110,\n" +
                "                \"l8_pro_wait_delivery\":3771,\n" +
                "                \"l8_max_wait_delivery\":992,\n" +
                "                \"l7_lock_wait_delivery\":2761,\n" +
                "                \"l7_intent_wait_delivery\":4608,\n" +
                "                \"l7_from_l9_wait_delivery\":179,\n" +
                "                \"l7_from_l8_wait_delivery\":163,\n" +
                "                \"l7_from_one_wait_delivery\":4,\n" +
                "                \"l8_lock_wait_delivery\":4470,\n" +
                "                \"l8_from_l9_wait_delivery\":316,\n" +
                "                \"l8_from_l7_wait_delivery\":52,\n" +
                "                \"l8_from_one_wait_delivery\":35,\n" +
                "                \"l9_lock_wait_delivery\":4222,\n" +
                "                \"l9_intent_wait_delivery\":607,\n" +
                "                \"l9_from_l8_wait_delivery\":138,\n" +
                "                \"l9_from_l7_wait_delivery\":15,\n" +
                "                \"l9_from_one_wait_delivery\":10,\n" +
                "                \"one_lock_wait_delivery\":380,\n" +
                "                \"one_from_l9_wait_delivery\":7,\n" +
                "                \"one_from_l8_wait_delivery\":8,\n" +
                "                \"one_from_l7_wait_delivery\":0,\n" +
                "                \"seq_num\":21\n" +
                "            },\n" +
                "            {\n" +
                "                \"data_time\":\"2023.02.22\",\n" +
                "                \"total_wait_delivery\":17885,\n" +
                "                \"l7_wait_delivery\":7948,\n" +
                "                \"l8_wait_delivery\":4684,\n" +
                "                \"l9_wait_delivery\":4868,\n" +
                "                \"one_wait_delivery\":385,\n" +
                "                \"l7_air_wait_delivery\":535,\n" +
                "                \"l7_pro_wait_delivery\":5083,\n" +
                "                \"l7_max_wait_delivery\":2330,\n" +
                "                \"l8_air_wait_delivery\":117,\n" +
                "                \"l8_pro_wait_delivery\":3584,\n" +
                "                \"l8_max_wait_delivery\":983,\n" +
                "                \"l7_lock_wait_delivery\":2894,\n" +
                "                \"l7_intent_wait_delivery\":4702,\n" +
                "                \"l7_from_l9_wait_delivery\":185,\n" +
                "                \"l7_from_l8_wait_delivery\":163,\n" +
                "                \"l7_from_one_wait_delivery\":4,\n" +
                "                \"l8_lock_wait_delivery\":4281,\n" +
                "                \"l8_from_l9_wait_delivery\":309,\n" +
                "                \"l8_from_l7_wait_delivery\":59,\n" +
                "                \"l8_from_one_wait_delivery\":35,\n" +
                "                \"l9_lock_wait_delivery\":4103,\n" +
                "                \"l9_intent_wait_delivery\":594,\n" +
                "                \"l9_from_l8_wait_delivery\":141,\n" +
                "                \"l9_from_l7_wait_delivery\":20,\n" +
                "                \"l9_from_one_wait_delivery\":10,\n" +
                "                \"one_lock_wait_delivery\":370,\n" +
                "                \"one_from_l9_wait_delivery\":7,\n" +
                "                \"one_from_l8_wait_delivery\":8,\n" +
                "                \"one_from_l7_wait_delivery\":0,\n" +
                "                \"seq_num\":20\n" +
                "            },\n" +
                "            {\n" +
                "                \"data_time\":\"2023.02.23\",\n" +
                "                \"total_wait_delivery\":17706,\n" +
                "                \"l7_wait_delivery\":8198,\n" +
                "                \"l8_wait_delivery\":4413,\n" +
                "                \"l9_wait_delivery\":4732,\n" +
                "                \"one_wait_delivery\":363,\n" +
                "                \"l7_air_wait_delivery\":552,\n" +
                "                \"l7_pro_wait_delivery\":5255,\n" +
                "                \"l7_max_wait_delivery\":2391,\n" +
                "                \"l8_air_wait_delivery\":122,\n" +
                "                \"l8_pro_wait_delivery\":3351,\n" +
                "                \"l8_max_wait_delivery\":940,\n" +
                "                \"l7_lock_wait_delivery\":3049,\n" +
                "                \"l7_intent_wait_delivery\":4789,\n" +
                "                \"l7_from_l9_wait_delivery\":188,\n" +
                "                \"l7_from_l8_wait_delivery\":168,\n" +
                "                \"l7_from_one_wait_delivery\":4,\n" +
                "                \"l8_lock_wait_delivery\":4015,\n" +
                "                \"l8_from_l9_wait_delivery\":303,\n" +
                "                \"l8_from_l7_wait_delivery\":63,\n" +
                "                \"l8_from_one_wait_delivery\":32,\n" +
                "                \"l9_lock_wait_delivery\":3976,\n" +
                "                \"l9_intent_wait_delivery\":577,\n" +
                "                \"l9_from_l8_wait_delivery\":146,\n" +
                "                \"l9_from_l7_wait_delivery\":23,\n" +
                "                \"l9_from_one_wait_delivery\":10,\n" +
                "                \"one_lock_wait_delivery\":348,\n" +
                "                \"one_from_l9_wait_delivery\":7,\n" +
                "                \"one_from_l8_wait_delivery\":8,\n" +
                "                \"one_from_l7_wait_delivery\":0,\n" +
                "                \"seq_num\":19\n" +
                "            },\n" +
                "            {\n" +
                "                \"data_time\":\"2023.02.24\",\n" +
                "                \"total_wait_delivery\":17456,\n" +
                "                \"l7_wait_delivery\":8415,\n" +
                "                \"l8_wait_delivery\":4133,\n" +
                "                \"l9_wait_delivery\":4578,\n" +
                "                \"one_wait_delivery\":330,\n" +
                "                \"l7_air_wait_delivery\":570,\n" +
                "                \"l7_pro_wait_delivery\":5411,\n" +
                "                \"l7_max_wait_delivery\":2434,\n" +
                "                \"l8_air_wait_delivery\":129,\n" +
                "                \"l8_pro_wait_delivery\":3125,\n" +
                "                \"l8_max_wait_delivery\":879,\n" +
                "                \"l7_lock_wait_delivery\":3171,\n" +
                "                \"l7_intent_wait_delivery\":4881,\n" +
                "                \"l7_from_l9_wait_delivery\":188,\n" +
                "                \"l7_from_l8_wait_delivery\":170,\n" +
                "                \"l7_from_one_wait_delivery\":5,\n" +
                "                \"l8_lock_wait_delivery\":3760,\n" +
                "                \"l8_from_l9_wait_delivery\":286,\n" +
                "                \"l8_from_l7_wait_delivery\":57,\n" +
                "                \"l8_from_one_wait_delivery\":30,\n" +
                "                \"l9_lock_wait_delivery\":3829,\n" +
                "                \"l9_intent_wait_delivery\":568,\n" +
                "                \"l9_from_l8_wait_delivery\":148,\n" +
                "                \"l9_from_l7_wait_delivery\":23,\n" +
                "                \"l9_from_one_wait_delivery\":10,\n" +
                "                \"one_lock_wait_delivery\":315,\n" +
                "                \"one_from_l9_wait_delivery\":7,\n" +
                "                \"one_from_l8_wait_delivery\":8,\n" +
                "                \"one_from_l7_wait_delivery\":0,\n" +
                "                \"seq_num\":18\n" +
                "            },\n" +
                "            {\n" +
                "                \"data_time\":\"2023.02.25\",\n" +
                "                \"total_wait_delivery\":17383,\n" +
                "                \"l7_wait_delivery\":8783,\n" +
                "                \"l8_wait_delivery\":3829,\n" +
                "                \"l9_wait_delivery\":4453,\n" +
                "                \"one_wait_delivery\":318,\n" +
                "                \"l7_air_wait_delivery\":608,\n" +
                "                \"l7_pro_wait_delivery\":5666,\n" +
                "                \"l7_max_wait_delivery\":2509,\n" +
                "                \"l8_air_wait_delivery\":143,\n" +
                "                \"l8_pro_wait_delivery\":2866,\n" +
                "                \"l8_max_wait_delivery\":820,\n" +
                "                \"l7_lock_wait_delivery\":3387,\n" +
                "                \"l7_intent_wait_delivery\":5019,\n" +
                "                \"l7_from_l9_wait_delivery\":200,\n" +
                "                \"l7_from_l8_wait_delivery\":172,\n" +
                "                \"l7_from_one_wait_delivery\":5,\n" +
                "                \"l8_lock_wait_delivery\":3475,\n" +
                "                \"l8_from_l9_wait_delivery\":272,\n" +
                "                \"l8_from_l7_wait_delivery\":53,\n" +
                "                \"l8_from_one_wait_delivery\":29,\n" +
                "                \"l9_lock_wait_delivery\":3719,\n" +
                "                \"l9_intent_wait_delivery\":552,\n" +
                "                \"l9_from_l8_wait_delivery\":147,\n" +
                "                \"l9_from_l7_wait_delivery\":25,\n" +
                "                \"l9_from_one_wait_delivery\":10,\n" +
                "                \"one_lock_wait_delivery\":306,\n" +
                "                \"one_from_l9_wait_delivery\":4,\n" +
                "                \"one_from_l8_wait_delivery\":8,\n" +
                "                \"one_from_l7_wait_delivery\":0,\n" +
                "                \"seq_num\":17\n" +
                "            },\n" +
                "            {\n" +
                "                \"data_time\":\"2023.02.26\",\n" +
                "                \"total_wait_delivery\":17634,\n" +
                "                \"l7_wait_delivery\":9251,\n" +
                "                \"l8_wait_delivery\":3653,\n" +
                "                \"l9_wait_delivery\":4408,\n" +
                "                \"one_wait_delivery\":322,\n" +
                "                \"l7_air_wait_delivery\":640,\n" +
                "                \"l7_pro_wait_delivery\":5996,\n" +
                "                \"l7_max_wait_delivery\":2615,\n" +
                "                \"l8_air_wait_delivery\":150,\n" +
                "                \"l8_pro_wait_delivery\":2742,\n" +
                "                \"l8_max_wait_delivery\":761,\n" +
                "                \"l7_lock_wait_delivery\":3662,\n" +
                "                \"l7_intent_wait_delivery\":5201,\n" +
                "                \"l7_from_l9_wait_delivery\":206,\n" +
                "                \"l7_from_l8_wait_delivery\":177,\n" +
                "                \"l7_from_one_wait_delivery\":5,\n" +
                "                \"l8_lock_wait_delivery\":3297,\n" +
                "                \"l8_from_l9_wait_delivery\":267,\n" +
                "                \"l8_from_l7_wait_delivery\":60,\n" +
                "                \"l8_from_one_wait_delivery\":29,\n" +
                "                \"l9_lock_wait_delivery\":3692,\n" +
                "                \"l9_intent_wait_delivery\":540,\n" +
                "                \"l9_from_l8_wait_delivery\":140,\n" +
                "                \"l9_from_l7_wait_delivery\":26,\n" +
                "                \"l9_from_one_wait_delivery\":10,\n" +
                "                \"one_lock_wait_delivery\":310,\n" +
                "                \"one_from_l9_wait_delivery\":4,\n" +
                "                \"one_from_l8_wait_delivery\":8,\n" +
                "                \"one_from_l7_wait_delivery\":0,\n" +
                "                \"seq_num\":16\n" +
                "            },\n" +
                "            {\n" +
                "                \"data_time\":\"2023.02.27\",\n" +
                "                \"total_wait_delivery\":16776,\n" +
                "                \"l7_wait_delivery\":9600,\n" +
                "                \"l8_wait_delivery\":3129,\n" +
                "                \"l9_wait_delivery\":3773,\n" +
                "                \"one_wait_delivery\":274,\n" +
                "                \"l7_air_wait_delivery\":686,\n" +
                "                \"l7_pro_wait_delivery\":6231,\n" +
                "                \"l7_max_wait_delivery\":2683,\n" +
                "                \"l8_air_wait_delivery\":154,\n" +
                "                \"l8_pro_wait_delivery\":2340,\n" +
                "                \"l8_max_wait_delivery\":635,\n" +
                "                \"l7_lock_wait_delivery\":3828,\n" +
                "                \"l7_intent_wait_delivery\":5379,\n" +
                "                \"l7_from_l9_wait_delivery\":211,\n" +
                "                \"l7_from_l8_wait_delivery\":176,\n" +
                "                \"l7_from_one_wait_delivery\":6,\n" +
                "                \"l8_lock_wait_delivery\":2826,\n" +
                "                \"l8_from_l9_wait_delivery\":227,\n" +
                "                \"l8_from_l7_wait_delivery\":52,\n" +
                "                \"l8_from_one_wait_delivery\":24,\n" +
                "                \"l9_lock_wait_delivery\":3183,\n" +
                "                \"l9_intent_wait_delivery\":447,\n" +
                "                \"l9_from_l8_wait_delivery\":112,\n" +
                "                \"l9_from_l7_wait_delivery\":24,\n" +
                "                \"l9_from_one_wait_delivery\":7,\n" +
                "                \"one_lock_wait_delivery\":263,\n" +
                "                \"one_from_l9_wait_delivery\":3,\n" +
                "                \"one_from_l8_wait_delivery\":8,\n" +
                "                \"one_from_l7_wait_delivery\":0,\n" +
                "                \"seq_num\":15\n" +
                "            },\n" +
                "            {\n" +
                "                \"data_time\":\"2023.02.28\",\n" +
                "                \"total_wait_delivery\":16145,\n" +
                "                \"l7_wait_delivery\":10274,\n" +
                "                \"l8_wait_delivery\":2539,\n" +
                "                \"l9_wait_delivery\":3101,\n" +
                "                \"one_wait_delivery\":231,\n" +
                "                \"l7_air_wait_delivery\":757,\n" +
                "                \"l7_pro_wait_delivery\":6714,\n" +
                "                \"l7_max_wait_delivery\":2803,\n" +
                "                \"l8_air_wait_delivery\":165,\n" +
                "                \"l8_pro_wait_delivery\":1845,\n" +
                "                \"l8_max_wait_delivery\":529,\n" +
                "                \"l7_lock_wait_delivery\":4131,\n" +
                "                \"l7_intent_wait_delivery\":5741,\n" +
                "                \"l7_from_l9_wait_delivery\":217,\n" +
                "                \"l7_from_l8_wait_delivery\":177,\n" +
                "                \"l7_from_one_wait_delivery\":8,\n" +
                "                \"l8_lock_wait_delivery\":2319,\n" +
                "                \"l8_from_l9_wait_delivery\":160,\n" +
                "                \"l8_from_l7_wait_delivery\":43,\n" +
                "                \"l8_from_one_wait_delivery\":17,\n" +
                "                \"l9_lock_wait_delivery\":2639,\n" +
                "                \"l9_intent_wait_delivery\":338,\n" +
                "                \"l9_from_l8_wait_delivery\":99,\n" +
                "                \"l9_from_l7_wait_delivery\":21,\n" +
                "                \"l9_from_one_wait_delivery\":4,\n" +
                "                \"one_lock_wait_delivery\":226,\n" +
                "                \"one_from_l9_wait_delivery\":1,\n" +
                "                \"one_from_l8_wait_delivery\":4,\n" +
                "                \"one_from_l7_wait_delivery\":0,\n" +
                "                \"seq_num\":14\n" +
                "            },\n" +
                "            {\n" +
                "                \"data_time\":\"2023.03.01\",\n" +
                "                \"total_wait_delivery\":16507,\n" +
                "                \"l7_wait_delivery\":10429,\n" +
                "                \"l8_wait_delivery\":2627,\n" +
                "                \"l9_wait_delivery\":3189,\n" +
                "                \"one_wait_delivery\":262,\n" +
                "                \"l7_air_wait_delivery\":769,\n" +
                "                \"l7_pro_wait_delivery\":6804,\n" +
                "                \"l7_max_wait_delivery\":2856,\n" +
                "                \"l8_air_wait_delivery\":170,\n" +
                "                \"l8_pro_wait_delivery\":1914,\n" +
                "                \"l8_max_wait_delivery\":543,\n" +
                "                \"l7_lock_wait_delivery\":4249,\n" +
                "                \"l7_intent_wait_delivery\":5780,\n" +
                "                \"l7_from_l9_wait_delivery\":208,\n" +
                "                \"l7_from_l8_wait_delivery\":183,\n" +
                "                \"l7_from_one_wait_delivery\":9,\n" +
                "                \"l8_lock_wait_delivery\":2403,\n" +
                "                \"l8_from_l9_wait_delivery\":162,\n" +
                "                \"l8_from_l7_wait_delivery\":44,\n" +
                "                \"l8_from_one_wait_delivery\":18,\n" +
                "                \"l9_lock_wait_delivery\":2719,\n" +
                "                \"l9_intent_wait_delivery\":332,\n" +
                "                \"l9_from_l8_wait_delivery\":101,\n" +
                "                \"l9_from_l7_wait_delivery\":33,\n" +
                "                \"l9_from_one_wait_delivery\":4,\n" +
                "                \"one_lock_wait_delivery\":255,\n" +
                "                \"one_from_l9_wait_delivery\":2,\n" +
                "                \"one_from_l8_wait_delivery\":5,\n" +
                "                \"one_from_l7_wait_delivery\":0,\n" +
                "                \"seq_num\":13\n" +
                "            },\n" +
                "            {\n" +
                "                \"data_time\":\"2023.03.02\",\n" +
                "                \"total_wait_delivery\":16740,\n" +
                "                \"l7_wait_delivery\":10544,\n" +
                "                \"l8_wait_delivery\":2674,\n" +
                "                \"l9_wait_delivery\":3254,\n" +
                "                \"one_wait_delivery\":268,\n" +
                "                \"l7_air_wait_delivery\":773,\n" +
                "                \"l7_pro_wait_delivery\":6886,\n" +
                "                \"l7_max_wait_delivery\":2885,\n" +
                "                \"l8_air_wait_delivery\":170,\n" +
                "                \"l8_pro_wait_delivery\":1965,\n" +
                "                \"l8_max_wait_delivery\":539,\n" +
                "                \"l7_lock_wait_delivery\":4324,\n" +
                "                \"l7_intent_wait_delivery\":5799,\n" +
                "                \"l7_from_l9_wait_delivery\":217,\n" +
                "                \"l7_from_l8_wait_delivery\":195,\n" +
                "                \"l7_from_one_wait_delivery\":9,\n" +
                "                \"l8_lock_wait_delivery\":2449,\n" +
                "                \"l8_from_l9_wait_delivery\":163,\n" +
                "                \"l8_from_l7_wait_delivery\":46,\n" +
                "                \"l8_from_one_wait_delivery\":16,\n" +
                "                \"l9_lock_wait_delivery\":2783,\n" +
                "                \"l9_intent_wait_delivery\":325,\n" +
                "                \"l9_from_l8_wait_delivery\":103,\n" +
                "                \"l9_from_l7_wait_delivery\":39,\n" +
                "                \"l9_from_one_wait_delivery\":4,\n" +
                "                \"one_lock_wait_delivery\":258,\n" +
                "                \"one_from_l9_wait_delivery\":2,\n" +
                "                \"one_from_l8_wait_delivery\":7,\n" +
                "                \"one_from_l7_wait_delivery\":1,\n" +
                "                \"seq_num\":12\n" +
                "            },\n" +
                "            {\n" +
                "                \"data_time\":\"2023.03.03\",\n" +
                "                \"total_wait_delivery\":17076,\n" +
                "                \"l7_wait_delivery\":10707,\n" +
                "                \"l8_wait_delivery\":2722,\n" +
                "                \"l9_wait_delivery\":3366,\n" +
                "                \"one_wait_delivery\":281,\n" +
                "                \"l7_air_wait_delivery\":791,\n" +
                "                \"l7_pro_wait_delivery\":7002,\n" +
                "                \"l7_max_wait_delivery\":2914,\n" +
                "                \"l8_air_wait_delivery\":178,\n" +
                "                \"l8_pro_wait_delivery\":2003,\n" +
                "                \"l8_max_wait_delivery\":541,\n" +
                "                \"l7_lock_wait_delivery\":4462,\n" +
                "                \"l7_intent_wait_delivery\":5819,\n" +
                "                \"l7_from_l9_wait_delivery\":215,\n" +
                "                \"l7_from_l8_wait_delivery\":202,\n" +
                "                \"l7_from_one_wait_delivery\":9,\n" +
                "                \"l8_lock_wait_delivery\":2487,\n" +
                "                \"l8_from_l9_wait_delivery\":165,\n" +
                "                \"l8_from_l7_wait_delivery\":53,\n" +
                "                \"l8_from_one_wait_delivery\":17,\n" +
                "                \"l9_lock_wait_delivery\":2893,\n" +
                "                \"l9_intent_wait_delivery\":323,\n" +
                "                \"l9_from_l8_wait_delivery\":100,\n" +
                "                \"l9_from_l7_wait_delivery\":46,\n" +
                "                \"l9_from_one_wait_delivery\":4,\n" +
                "                \"one_lock_wait_delivery\":271,\n" +
                "                \"one_from_l9_wait_delivery\":3,\n" +
                "                \"one_from_l8_wait_delivery\":6,\n" +
                "                \"one_from_l7_wait_delivery\":1,\n" +
                "                \"seq_num\":11\n" +
                "            },\n" +
                "            {\n" +
                "                \"data_time\":\"2023.03.04\",\n" +
                "                \"total_wait_delivery\":17772,\n" +
                "                \"l7_wait_delivery\":10998,\n" +
                "                \"l8_wait_delivery\":2933,\n" +
                "                \"l9_wait_delivery\":3532,\n" +
                "                \"one_wait_delivery\":309,\n" +
                "                \"l7_air_wait_delivery\":827,\n" +
                "                \"l7_pro_wait_delivery\":7204,\n" +
                "                \"l7_max_wait_delivery\":2967,\n" +
                "                \"l8_air_wait_delivery\":184,\n" +
                "                \"l8_pro_wait_delivery\":2183,\n" +
                "                \"l8_max_wait_delivery\":566,\n" +
                "                \"l7_lock_wait_delivery\":4717,\n" +
                "                \"l7_intent_wait_delivery\":5854,\n" +
                "                \"l7_from_l9_wait_delivery\":215,\n" +
                "                \"l7_from_l8_wait_delivery\":203,\n" +
                "                \"l7_from_one_wait_delivery\":9,\n" +
                "                \"l8_lock_wait_delivery\":2695,\n" +
                "                \"l8_from_l9_wait_delivery\":165,\n" +
                "                \"l8_from_l7_wait_delivery\":56,\n" +
                "                \"l8_from_one_wait_delivery\":17,\n" +
                "                \"l9_lock_wait_delivery\":3054,\n" +
                "                \"l9_intent_wait_delivery\":321,\n" +
                "                \"l9_from_l8_wait_delivery\":101,\n" +
                "                \"l9_from_l7_wait_delivery\":52,\n" +
                "                \"l9_from_one_wait_delivery\":4,\n" +
                "                \"one_lock_wait_delivery\":299,\n" +
                "                \"one_from_l9_wait_delivery\":3,\n" +
                "                \"one_from_l8_wait_delivery\":6,\n" +
                "                \"one_from_l7_wait_delivery\":1,\n" +
                "                \"seq_num\":10\n" +
                "            },\n" +
                "            {\n" +
                "                \"data_time\":\"2023.03.05\",\n" +
                "                \"total_wait_delivery\":18443,\n" +
                "                \"l7_wait_delivery\":11297,\n" +
                "                \"l8_wait_delivery\":3117,\n" +
                "                \"l9_wait_delivery\":3690,\n" +
                "                \"one_wait_delivery\":339,\n" +
                "                \"l7_air_wait_delivery\":865,\n" +
                "                \"l7_pro_wait_delivery\":7403,\n" +
                "                \"l7_max_wait_delivery\":3029,\n" +
                "                \"l8_air_wait_delivery\":189,\n" +
                "                \"l8_pro_wait_delivery\":2349,\n" +
                "                \"l8_max_wait_delivery\":579,\n" +
                "                \"l7_lock_wait_delivery\":4975,\n" +
                "                \"l7_intent_wait_delivery\":5895,\n" +
                "                \"l7_from_l9_wait_delivery\":215,\n" +
                "                \"l7_from_l8_wait_delivery\":203,\n" +
                "                \"l7_from_one_wait_delivery\":9,\n" +
                "                \"l8_lock_wait_delivery\":2878,\n" +
                "                \"l8_from_l9_wait_delivery\":164,\n" +
                "                \"l8_from_l7_wait_delivery\":58,\n" +
                "                \"l8_from_one_wait_delivery\":17,\n" +
                "                \"l9_lock_wait_delivery\":3213,\n" +
                "                \"l9_intent_wait_delivery\":318,\n" +
                "                \"l9_from_l8_wait_delivery\":101,\n" +
                "                \"l9_from_l7_wait_delivery\":54,\n" +
                "                \"l9_from_one_wait_delivery\":4,\n" +
                "                \"one_lock_wait_delivery\":329,\n" +
                "                \"one_from_l9_wait_delivery\":3,\n" +
                "                \"one_from_l8_wait_delivery\":6,\n" +
                "                \"one_from_l7_wait_delivery\":1,\n" +
                "                \"seq_num\":9\n" +
                "            },\n" +
                "            {\n" +
                "                \"data_time\":\"2023.03.06\",\n" +
                "                \"total_wait_delivery\":18414,\n" +
                "                \"l7_wait_delivery\":11460,\n" +
                "                \"l8_wait_delivery\":2991,\n" +
                "                \"l9_wait_delivery\":3630,\n" +
                "                \"one_wait_delivery\":333,\n" +
                "                \"l7_air_wait_delivery\":886,\n" +
                "                \"l7_pro_wait_delivery\":7524,\n" +
                "                \"l7_max_wait_delivery\":3050,\n" +
                "                \"l8_air_wait_delivery\":187,\n" +
                "                \"l8_pro_wait_delivery\":2251,\n" +
                "                \"l8_max_wait_delivery\":553,\n" +
                "                \"l7_lock_wait_delivery\":5115,\n" +
                "                \"l7_intent_wait_delivery\":5905,\n" +
                "                \"l7_from_l9_wait_delivery\":220,\n" +
                "                \"l7_from_l8_wait_delivery\":210,\n" +
                "                \"l7_from_one_wait_delivery\":10,\n" +
                "                \"l8_lock_wait_delivery\":2748,\n" +
                "                \"l8_from_l9_wait_delivery\":161,\n" +
                "                \"l8_from_l7_wait_delivery\":68,\n" +
                "                \"l8_from_one_wait_delivery\":14,\n" +
                "                \"l9_lock_wait_delivery\":3163,\n" +
                "                \"l9_intent_wait_delivery\":309,\n" +
                "                \"l9_from_l8_wait_delivery\":99,\n" +
                "                \"l9_from_l7_wait_delivery\":55,\n" +
                "                \"l9_from_one_wait_delivery\":4,\n" +
                "                \"one_lock_wait_delivery\":323,\n" +
                "                \"one_from_l9_wait_delivery\":3,\n" +
                "                \"one_from_l8_wait_delivery\":6,\n" +
                "                \"one_from_l7_wait_delivery\":1,\n" +
                "                \"seq_num\":8\n" +
                "            },\n" +
                "            {\n" +
                "                \"data_time\":\"2023.03.07\",\n" +
                "                \"total_wait_delivery\":18435,\n" +
                "                \"l7_wait_delivery\":11618,\n" +
                "                \"l8_wait_delivery\":2928,\n" +
                "                \"l9_wait_delivery\":3540,\n" +
                "                \"one_wait_delivery\":349,\n" +
                "                \"l7_air_wait_delivery\":918,\n" +
                "                \"l7_pro_wait_delivery\":7615,\n" +
                "                \"l7_max_wait_delivery\":3085,\n" +
                "                \"l8_air_wait_delivery\":197,\n" +
                "                \"l8_pro_wait_delivery\":2208,\n" +
                "                \"l8_max_wait_delivery\":523,\n" +
                "                \"l7_lock_wait_delivery\":5242,\n" +
                "                \"l7_intent_wait_delivery\":5931,\n" +
                "                \"l7_from_l9_wait_delivery\":225,\n" +
                "                \"l7_from_l8_wait_delivery\":210,\n" +
                "                \"l7_from_one_wait_delivery\":10,\n" +
                "                \"l8_lock_wait_delivery\":2686,\n" +
                "                \"l8_from_l9_wait_delivery\":159,\n" +
                "                \"l8_from_l7_wait_delivery\":69,\n" +
                "                \"l8_from_one_wait_delivery\":14,\n" +
                "                \"l9_lock_wait_delivery\":3092,\n" +
                "                \"l9_intent_wait_delivery\":297,\n" +
                "                \"l9_from_l8_wait_delivery\":95,\n" +
                "                \"l9_from_l7_wait_delivery\":52,\n" +
                "                \"l9_from_one_wait_delivery\":4,\n" +
                "                \"one_lock_wait_delivery\":337,\n" +
                "                \"one_from_l9_wait_delivery\":4,\n" +
                "                \"one_from_l8_wait_delivery\":7,\n" +
                "                \"one_from_l7_wait_delivery\":1,\n" +
                "                \"seq_num\":7\n" +
                "            },\n" +
                "            {\n" +
                "                \"data_time\":\"2023.03.08\",\n" +
                "                \"total_wait_delivery\":18527,\n" +
                "                \"l7_wait_delivery\":11838,\n" +
                "                \"l8_wait_delivery\":2884,\n" +
                "                \"l9_wait_delivery\":3474,\n" +
                "                \"one_wait_delivery\":331,\n" +
                "                \"l7_air_wait_delivery\":947,\n" +
                "                \"l7_pro_wait_delivery\":7763,\n" +
                "                \"l7_max_wait_delivery\":3128,\n" +
                "                \"l8_air_wait_delivery\":204,\n" +
                "                \"l8_pro_wait_delivery\":2157,\n" +
                "                \"l8_max_wait_delivery\":523,\n" +
                "                \"l7_lock_wait_delivery\":5433,\n" +
                "                \"l7_intent_wait_delivery\":5957,\n" +
                "                \"l7_from_l9_wait_delivery\":226,\n" +
                "                \"l7_from_l8_wait_delivery\":212,\n" +
                "                \"l7_from_one_wait_delivery\":10,\n" +
                "                \"l8_lock_wait_delivery\":2649,\n" +
                "                \"l8_from_l9_wait_delivery\":154,\n" +
                "                \"l8_from_l7_wait_delivery\":68,\n" +
                "                \"l8_from_one_wait_delivery\":13,\n" +
                "                \"l9_lock_wait_delivery\":3039,\n" +
                "                \"l9_intent_wait_delivery\":285,\n" +
                "                \"l9_from_l8_wait_delivery\":94,\n" +
                "                \"l9_from_l7_wait_delivery\":52,\n" +
                "                \"l9_from_one_wait_delivery\":4,\n" +
                "                \"one_lock_wait_delivery\":320,\n" +
                "                \"one_from_l9_wait_delivery\":4,\n" +
                "                \"one_from_l8_wait_delivery\":7,\n" +
                "                \"one_from_l7_wait_delivery\":0,\n" +
                "                \"seq_num\":6\n" +
                "            },\n" +
                "            {\n" +
                "                \"data_time\":\"2023.03.09\",\n" +
                "                \"total_wait_delivery\":18262,\n" +
                "                \"l7_wait_delivery\":11929,\n" +
                "                \"l8_wait_delivery\":2715,\n" +
                "                \"l9_wait_delivery\":3306,\n" +
                "                \"one_wait_delivery\":312,\n" +
                "                \"l7_air_wait_delivery\":954,\n" +
                "                \"l7_pro_wait_delivery\":7825,\n" +
                "                \"l7_max_wait_delivery\":3150,\n" +
                "                \"l8_air_wait_delivery\":203,\n" +
                "                \"l8_pro_wait_delivery\":2027,\n" +
                "                \"l8_max_wait_delivery\":485,\n" +
                "                \"l7_lock_wait_delivery\":5511,\n" +
                "                \"l7_intent_wait_delivery\":5970,\n" +
                "                \"l7_from_l9_wait_delivery\":227,\n" +
                "                \"l7_from_l8_wait_delivery\":211,\n" +
                "                \"l7_from_one_wait_delivery\":10,\n" +
                "                \"l8_lock_wait_delivery\":2476,\n" +
                "                \"l8_from_l9_wait_delivery\":158,\n" +
                "                \"l8_from_l7_wait_delivery\":68,\n" +
                "                \"l8_from_one_wait_delivery\":13,\n" +
                "                \"l9_lock_wait_delivery\":2879,\n" +
                "                \"l9_intent_wait_delivery\":277,\n" +
                "                \"l9_from_l8_wait_delivery\":93,\n" +
                "                \"l9_from_l7_wait_delivery\":53,\n" +
                "                \"l9_from_one_wait_delivery\":4,\n" +
                "                \"one_lock_wait_delivery\":301,\n" +
                "                \"one_from_l9_wait_delivery\":4,\n" +
                "                \"one_from_l8_wait_delivery\":7,\n" +
                "                \"one_from_l7_wait_delivery\":0,\n" +
                "                \"seq_num\":5\n" +
                "            },\n" +
                "            {\n" +
                "                \"data_time\":\"2023.03.10\",\n" +
                "                \"total_wait_delivery\":17999,\n" +
                "                \"l7_wait_delivery\":12024,\n" +
                "                \"l8_wait_delivery\":2558,\n" +
                "                \"l9_wait_delivery\":3128,\n" +
                "                \"one_wait_delivery\":289,\n" +
                "                \"l7_air_wait_delivery\":962,\n" +
                "                \"l7_pro_wait_delivery\":7881,\n" +
                "                \"l7_max_wait_delivery\":3181,\n" +
                "                \"l8_air_wait_delivery\":204,\n" +
                "                \"l8_pro_wait_delivery\":1905,\n" +
                "                \"l8_max_wait_delivery\":449,\n" +
                "                \"l7_lock_wait_delivery\":5594,\n" +
                "                \"l7_intent_wait_delivery\":5981,\n" +
                "                \"l7_from_l9_wait_delivery\":227,\n" +
                "                \"l7_from_l8_wait_delivery\":212,\n" +
                "                \"l7_from_one_wait_delivery\":10,\n" +
                "                \"l8_lock_wait_delivery\":2317,\n" +
                "                \"l8_from_l9_wait_delivery\":158,\n" +
                "                \"l8_from_l7_wait_delivery\":70,\n" +
                "                \"l8_from_one_wait_delivery\":13,\n" +
                "                \"l9_lock_wait_delivery\":2722,\n" +
                "                \"l9_intent_wait_delivery\":263,\n" +
                "                \"l9_from_l8_wait_delivery\":91,\n" +
                "                \"l9_from_l7_wait_delivery\":49,\n" +
                "                \"l9_from_one_wait_delivery\":3,\n" +
                "                \"one_lock_wait_delivery\":278,\n" +
                "                \"one_from_l9_wait_delivery\":4,\n" +
                "                \"one_from_l8_wait_delivery\":7,\n" +
                "                \"one_from_l7_wait_delivery\":0,\n" +
                "                \"seq_num\":4\n" +
                "            },\n" +
                "            {\n" +
                "                \"data_time\":\"2023.03.11\",\n" +
                "                \"total_wait_delivery\":17711,\n" +
                "                \"l7_wait_delivery\":11742,\n" +
                "                \"l8_wait_delivery\":2552,\n" +
                "                \"l9_wait_delivery\":3119,\n" +
                "                \"one_wait_delivery\":298,\n" +
                "                \"l7_air_wait_delivery\":986,\n" +
                "                \"l7_pro_wait_delivery\":7679,\n" +
                "                \"l7_max_wait_delivery\":3077,\n" +
                "                \"l8_air_wait_delivery\":209,\n" +
                "                \"l8_pro_wait_delivery\":1907,\n" +
                "                \"l8_max_wait_delivery\":436,\n" +
                "                \"l7_lock_wait_delivery\":5758,\n" +
                "                \"l7_intent_wait_delivery\":5538,\n" +
                "                \"l7_from_l9_wait_delivery\":225,\n" +
                "                \"l7_from_l8_wait_delivery\":211,\n" +
                "                \"l7_from_one_wait_delivery\":10,\n" +
                "                \"l8_lock_wait_delivery\":2314,\n" +
                "                \"l8_from_l9_wait_delivery\":156,\n" +
                "                \"l8_from_l7_wait_delivery\":70,\n" +
                "                \"l8_from_one_wait_delivery\":12,\n" +
                "                \"l9_lock_wait_delivery\":2727,\n" +
                "                \"l9_intent_wait_delivery\":256,\n" +
                "                \"l9_from_l8_wait_delivery\":87,\n" +
                "                \"l9_from_l7_wait_delivery\":46,\n" +
                "                \"l9_from_one_wait_delivery\":3,\n" +
                "                \"one_lock_wait_delivery\":287,\n" +
                "                \"one_from_l9_wait_delivery\":4,\n" +
                "                \"one_from_l8_wait_delivery\":7,\n" +
                "                \"one_from_l7_wait_delivery\":0,\n" +
                "                \"seq_num\":3\n" +
                "            },\n" +
                "            {\n" +
                "                \"data_time\":\"2023.03.12\",\n" +
                "                \"total_wait_delivery\":17749,\n" +
                "                \"l7_wait_delivery\":11711,\n" +
                "                \"l8_wait_delivery\":2586,\n" +
                "                \"l9_wait_delivery\":3144,\n" +
                "                \"one_wait_delivery\":308,\n" +
                "                \"l7_air_wait_delivery\":1011,\n" +
                "                \"l7_pro_wait_delivery\":7658,\n" +
                "                \"l7_max_wait_delivery\":3042,\n" +
                "                \"l8_air_wait_delivery\":219,\n" +
                "                \"l8_pro_wait_delivery\":1920,\n" +
                "                \"l8_max_wait_delivery\":447,\n" +
                "                \"l7_lock_wait_delivery\":5982,\n" +
                "                \"l7_intent_wait_delivery\":5282,\n" +
                "                \"l7_from_l9_wait_delivery\":227,\n" +
                "                \"l7_from_l8_wait_delivery\":209,\n" +
                "                \"l7_from_one_wait_delivery\":11,\n" +
                "                \"l8_lock_wait_delivery\":2349,\n" +
                "                \"l8_from_l9_wait_delivery\":155,\n" +
                "                \"l8_from_l7_wait_delivery\":71,\n" +
                "                \"l8_from_one_wait_delivery\":11,\n" +
                "                \"l9_lock_wait_delivery\":2756,\n" +
                "                \"l9_intent_wait_delivery\":250,\n" +
                "                \"l9_from_l8_wait_delivery\":88,\n" +
                "                \"l9_from_l7_wait_delivery\":47,\n" +
                "                \"l9_from_one_wait_delivery\":3,\n" +
                "                \"one_lock_wait_delivery\":298,\n" +
                "                \"one_from_l9_wait_delivery\":4,\n" +
                "                \"one_from_l8_wait_delivery\":6,\n" +
                "                \"one_from_l7_wait_delivery\":0,\n" +
                "                \"seq_num\":2\n" +
                "            },\n" +
                "            {\n" +
                "                \"data_time\":\"2023.03.13\",\n" +
                "                \"total_wait_delivery\":17732,\n" +
                "                \"l7_wait_delivery\":11696,\n" +
                "                \"l8_wait_delivery\":2591,\n" +
                "                \"l9_wait_delivery\":3142,\n" +
                "                \"one_wait_delivery\":303,\n" +
                "                \"l7_air_wait_delivery\":1011,\n" +
                "                \"l7_pro_wait_delivery\":7647,\n" +
                "                \"l7_max_wait_delivery\":3038,\n" +
                "                \"l8_air_wait_delivery\":219,\n" +
                "                \"l8_pro_wait_delivery\":1923,\n" +
                "                \"l8_max_wait_delivery\":449,\n" +
                "                \"l7_lock_wait_delivery\":5978,\n" +
                "                \"l7_intent_wait_delivery\":5272,\n" +
                "                \"l7_from_l9_wait_delivery\":226,\n" +
                "                \"l7_from_l8_wait_delivery\":209,\n" +
                "                \"l7_from_one_wait_delivery\":11,\n" +
                "                \"l8_lock_wait_delivery\":2351,\n" +
                "                \"l8_from_l9_wait_delivery\":155,\n" +
                "                \"l8_from_l7_wait_delivery\":74,\n" +
                "                \"l8_from_one_wait_delivery\":11,\n" +
                "                \"l9_lock_wait_delivery\":2754,\n" +
                "                \"l9_intent_wait_delivery\":250,\n" +
                "                \"l9_from_l8_wait_delivery\":88,\n" +
                "                \"l9_from_l7_wait_delivery\":47,\n" +
                "                \"l9_from_one_wait_delivery\":3,\n" +
                "                \"one_lock_wait_delivery\":293,\n" +
                "                \"one_from_l9_wait_delivery\":4,\n" +
                "                \"one_from_l8_wait_delivery\":6,\n" +
                "                \"one_from_l7_wait_delivery\":0,\n" +
                "                \"seq_num\":1\n" +
                "            }\n" +
                "        ],\n" +
                "        \"totalCount\":31\n" +
                "    }\n" +
                "}";
        Map map = JSON.parseObject(mapString, Map.class);
        System.out.println(JSON.toJSONString(map));
        StringWriter stringWriter = new StringWriter();
        Template template = config.getTemplate("cxotest.ftl");
        template.process(map, stringWriter);
        String s = stringWriter.getBuffer().toString();
        System.out.println(s);
    }


    @Test
    public void multiList() throws IOException, TemplateException {
        String mapString = "{\n" +
                "    \"mulit_api_test01\":{\n" +
                "        \"total\":{\n" +
                "            \"dataList\":[\n" +
                "                {\n" +
                "                    \"pdi_intime_rate\":\"99.9%\",\n" +
                "                    \"first_detect_intime_rate\":\"99.8%\",\n" +
                "                    \"urgent_delivery_rate\":\"12.5%\",\n" +
                "                    \"noappoint_detect_rate\":\"17.7%\",\n" +
                "                    \"stock_intime_rate\":\"93.9%\"\n" +
                "                }\n" +
                "            ]\n" +
                "        },\n" +
                "        \"day\":{\n" +
                "            \"dataList\":[\n" +
                "                {\n" +
                "                    \"data_date\":\"01\",\n" +
                "                    \"pdi_intime_num\":13,\n" +
                "                    \"pds_late_num\":0,\n" +
                "                    \"pdi_intime_rate\":100,\n" +
                "                    \"avg_pdi_intime_rate\":99.5,\n" +
                "                    \"first_detect_intime_num\":11,\n" +
                "                    \"first_detect_late_num\":0,\n" +
                "                    \"first_detect_intime_rate\":100,\n" +
                "                    \"avg_first_detect_intime_rate\":99.7\n" +
                "                },\n" +
                "                {\n" +
                "                    \"data_date\":\"02\",\n" +
                "                    \"pdi_intime_num\":22,\n" +
                "                    \"pds_late_num\":0,\n" +
                "                    \"pdi_intime_rate\":100,\n" +
                "                    \"avg_pdi_intime_rate\":99.5,\n" +
                "                    \"first_detect_intime_num\":21,\n" +
                "                    \"first_detect_late_num\":0,\n" +
                "                    \"first_detect_intime_rate\":100,\n" +
                "                    \"avg_first_detect_intime_rate\":99.7\n" +
                "                },\n" +
                "                {\n" +
                "                    \"data_date\":\"03\",\n" +
                "                    \"pdi_intime_num\":30,\n" +
                "                    \"pds_late_num\":0,\n" +
                "                    \"pdi_intime_rate\":100,\n" +
                "                    \"avg_pdi_intime_rate\":99.5,\n" +
                "                    \"first_detect_intime_num\":27,\n" +
                "                    \"first_detect_late_num\":0,\n" +
                "                    \"first_detect_intime_rate\":100,\n" +
                "                    \"avg_first_detect_intime_rate\":99.7\n" +
                "                },\n" +
                "                {\n" +
                "                    \"data_date\":\"04\",\n" +
                "                    \"pdi_intime_num\":77,\n" +
                "                    \"pds_late_num\":0,\n" +
                "                    \"pdi_intime_rate\":100,\n" +
                "                    \"avg_pdi_intime_rate\":99.5,\n" +
                "                    \"first_detect_intime_num\":72,\n" +
                "                    \"first_detect_late_num\":0,\n" +
                "                    \"first_detect_intime_rate\":100,\n" +
                "                    \"avg_first_detect_intime_rate\":99.7\n" +
                "                },\n" +
                "                {\n" +
                "                    \"data_date\":\"05\",\n" +
                "                    \"pdi_intime_num\":101,\n" +
                "                    \"pds_late_num\":0,\n" +
                "                    \"pdi_intime_rate\":100,\n" +
                "                    \"avg_pdi_intime_rate\":99.5,\n" +
                "                    \"first_detect_intime_num\":90,\n" +
                "                    \"first_detect_late_num\":0,\n" +
                "                    \"first_detect_intime_rate\":100,\n" +
                "                    \"avg_first_detect_intime_rate\":99.7\n" +
                "                },\n" +
                "                {\n" +
                "                    \"data_date\":\"06\",\n" +
                "                    \"pdi_intime_num\":77,\n" +
                "                    \"pds_late_num\":1,\n" +
                "                    \"pdi_intime_rate\":98.7,\n" +
                "                    \"avg_pdi_intime_rate\":99.5,\n" +
                "                    \"first_detect_intime_num\":72,\n" +
                "                    \"first_detect_late_num\":1,\n" +
                "                    \"first_detect_intime_rate\":98.6,\n" +
                "                    \"avg_first_detect_intime_rate\":99.7\n" +
                "                },\n" +
                "                {\n" +
                "                    \"data_date\":\"07\",\n" +
                "                    \"pdi_intime_num\":112,\n" +
                "                    \"pds_late_num\":1,\n" +
                "                    \"pdi_intime_rate\":99.1,\n" +
                "                    \"avg_pdi_intime_rate\":99.5,\n" +
                "                    \"first_detect_intime_num\":99,\n" +
                "                    \"first_detect_late_num\":1,\n" +
                "                    \"first_detect_intime_rate\":99,\n" +
                "                    \"avg_first_detect_intime_rate\":99.7\n" +
                "                },\n" +
                "                {\n" +
                "                    \"data_date\":\"08\",\n" +
                "                    \"pdi_intime_num\":181,\n" +
                "                    \"pds_late_num\":4,\n" +
                "                    \"pdi_intime_rate\":97.8,\n" +
                "                    \"avg_pdi_intime_rate\":99.5,\n" +
                "                    \"first_detect_intime_num\":170,\n" +
                "                    \"first_detect_late_num\":4,\n" +
                "                    \"first_detect_intime_rate\":97.7,\n" +
                "                    \"avg_first_detect_intime_rate\":99.7\n" +
                "                },\n" +
                "                {\n" +
                "                    \"data_date\":\"09\",\n" +
                "                    \"pdi_intime_num\":147,\n" +
                "                    \"pds_late_num\":2,\n" +
                "                    \"pdi_intime_rate\":98.7,\n" +
                "                    \"avg_pdi_intime_rate\":99.5,\n" +
                "                    \"first_detect_intime_num\":136,\n" +
                "                    \"first_detect_late_num\":1,\n" +
                "                    \"first_detect_intime_rate\":99.3,\n" +
                "                    \"avg_first_detect_intime_rate\":99.7\n" +
                "                },\n" +
                "                {\n" +
                "                    \"data_date\":\"10\",\n" +
                "                    \"pdi_intime_num\":84,\n" +
                "                    \"pds_late_num\":0,\n" +
                "                    \"pdi_intime_rate\":100,\n" +
                "                    \"avg_pdi_intime_rate\":99.5,\n" +
                "                    \"first_detect_intime_num\":60,\n" +
                "                    \"first_detect_late_num\":0,\n" +
                "                    \"first_detect_intime_rate\":100,\n" +
                "                    \"avg_first_detect_intime_rate\":99.7\n" +
                "                }\n" +
                "            ]\n" +
                "        }\n" +
                "    }\n" +
                "}";

        Map map = JSON.parseObject(mapString, Map.class);
        System.out.println(JSON.toJSONString(map));
        StringWriter stringWriter = new StringWriter();
        Template template = config.getTemplate("multilist.ftl");
        template.process(map, stringWriter);
        String s = stringWriter.getBuffer().toString();
        System.out.println(s);

    }

}
